dataset_name = "tiny-imagenet-200"
# dataset_name = "imagenet256"
dataset_path = "data/tiny-imagenet-200/train"
# dataset_path = "/scratch/ssd001/datasets/imagenet256/train"
model_selection = "RN50"
n_components = 1024
n_neighbours = 5
n_trees = 5
partition_size = 500
text_list_file = "data/tiny-imagenet-200/words.txt"
